name: Daniel Madson
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Daniel Madson Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161614'
    - '#ffffff'
    - '#4d4a43'
    - '#97907e'
    - '#b9b6a7'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
