name: Daniel Madson
favicon: null
layout_spectrum: 0.75013
typography_spectrum: 1
title: Daniel Madson Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161614'
    - '#ffffff'
    - '#4d4a43'
    - '#97907e'
    - '#b9b6a7'
  brandStrength: 0.8125
  lightness: 0.14373446092940867
  saturation: 0.375
  rhythmicContrast: 0.8911617004778236
purpose: []
